name = "Timers"
uuid = "21f18d07-b854-4dab-86f0-c15a3821819a"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.5"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
